version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask_resume_chatbot
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production  # Change this for production environment
    volumes:
      - .:/app
    expose:
      - "5000"  # Expose Flask app port to other containers in the same network, but not to the host
    networks:
      - flask_network
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom Nginx configuration
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - flask-app  # Ensure Flask app starts before Nginx
    networks:
      - flask_network
    restart: always

networks:
  flask_network:
    driver: bridge

