services:
  flask-app:
    build: .
    container_name: flask_resume_chatbot
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production  # Change this for production environment
    volumes:
      - .:/app
    expose:
      - "5050"  # Expose Flask app port to other containers in the same network, but not to the host
    ports:
      - "5050:5050"
    networks:
      - flask_network
    restart: always


networks:
  flask_network:
    driver: bridge

